package de.grannath.pof.dsl

enum class BodyArmour(override val printName: String) : Printable {
    // STR
    PLATE_VEST("Plate Vest"),
    CHESTPLATE("Chestplate"),
    COPPER_PLATE("Copper Plate"),
    WAR_PLATE("War Plate"),
    FULL_PLATE("Full Plate"),
    ARENA_PLATE("Arena Plate"),
    LORDLY_PLATE("Lordly Plate"),
    BRONZE_PLATE("Bronze Plate"),
    BATTLE_PLATE("Battle Plate"),
    SUN_PLATE("Sun Plate"),
    COLOSSEUM_PLATE("Colosseum Plate"),
    MAJESTIC_PLATE("Majestic Plate"),
    GOLDEN_PLATE("Golden Plate"),
    CRUSADER_PLATE("Crusader Plate"),
    ASTRAL_PLATE("Astral Plate"),
    GLADIATOR_PLATE("Gladiator Plate"),
    GLORIOUS_PLATE("Glorious Plate"),
    // DEX
    SHABBY_JERKIN("Shabby Jerkin"),
    STRAPPED_LEATHER("Strapped Leather"),
    BUCKSKIN_TUNIC("Buckskin Tunic"),
    WILD_LEATHER("Wild Leather"),
    FULL_LEATHER("Full Leather"),
    SUN_LEATHER("Sun Leather"),
    THIEFS_GARB("Thief's Garb"),
    EELSKIN_TUNIC("Eelskin Tunic"),
    FRONTIER_LEATHER("Frontier Leather"),
    GLORIOUS_LEATHER("Glorious Leather"),
    CORONAL_LEATHER("Coronal Leather"),
    CUTTHROATS_GARB("Cutthroat's Garb"),
    SHARKSKIN_TUNIC("Sharkskin Tunic"),
    DESTINY_LEATHER("Destiny Leather"),
    EXQUISITE_LEATHER("Exquisite Leather"),
    ZODIAC_LEATHER("Zodiac Leather"),
    ASSASSINS_GARB("Assassin's Garb"),
    // INT
    SIMPLE_ROBE("Simple Robe"),
    SILKEN_VEST("Silken Vest"),
    SCHOLARS_ROBE("Scholar's Robe"),
    SILKEN_GARB("Silken Garb"),
    MAGES_VESTMENT("Mage's Vestment"),
    SILK_ROBE("Silk Robe"),
    CABALIST_REGALIA("Cabalist Regalia"),
    SAGES_ROBE("Sage's Robe"),
    SILKEN_WRAP("Silken Wrap"),
    CONJURERS_VESTMENT("Conjurer's Vestment"),
    SPIDERSILK_ROBE("Spidersilk Robe"),
    DESTROYER_REGALIA("Destroyer Regalia"),
    SAVANTS_ROBE("Savant's Robe"),
    NECROMANCER_SILKS("Necromancer Silks"),
    OCCULTISTS_VESTMENT("Occultist's Vestment"),
    WIDOWSILK_ROBE("Widowsilk Robe"),
    VAAL_REGALIA("Vaal Regalia"),
    // STR/INT
    CHAINMAIL_VEST("Chainmail Vest"),
    CHAINMAIL_TUNIC("Chainmail Tunic"),
    RINGMAIL_COAT("Ringmail Coat"),
    CHAINMAIL_DOUBLET("Chainmail Doublet"),
    FULL_RINGMAIL("Full Ringmail"),
    FULL_CHAINMAIL("Full Chainmail"),
    HOLY_CHAINMAIL("Holy Chainmail"),
    LATTICED_RINGMAIL("Latticed Ringmail"),
    CRUSADER_CHAINMAIL("Crusader Chainmail"),
    ORNATE_RINGMAIL("Ornate Ringmail"),
    CHAIN_HAUBERK("Chain Hauberk"),
    DEVOUT_CHAINMAIL("Devout Chainmail"),
    LORICATED_RINGMAIL("Loricated Ringmail"),
    CONQUEST_CHAINMAIL("Conquest Chainmail"),
    ELEGANT_RINGMAIL("Elegant Ringmail"),
    SAINTS_HAUBERK("Saint's Hauberk"),
    SAINTLY_CHAINMAIL("Saintly Chainmail"),
    // STR/DEX
    LIGHT_BRIGANDINE("Light Brigandine"),
    SCALE_DOUBLET("Scale Doublet"),
    INFANTRY_BRIGANDINE("Infantry Brigandine"),
    FULL_SCALE_ARMOUR("Full Scale Armour"),
    SOLDIERS_BRIGANDINE("Soldier's Brigandine"),
    FIELD_LAMELLAR("Field Lamellar"),
    WYRMSCALE_DOUBLET("Wyrmscale Doublet"),
    HUSSAR_BRIGANDINE("Hussar Brigandine"),
    FULL_WYRMSCALE("Full Wyrmscale"),
    COMMANDERS_BRIGANDINE("Commander's Brigandine"),
    BATTLE_LAMELLAR("Battle Lamellar"),
    DRAGONSCALE_DOUBLET("Dragonscale Doublet"),
    DESERT_BRIGANDINE("Desert Brigandine"),
    FULL_DRAGONSCALE("Full Dragonscale"),
    GENERALS_BRIGANDINE("General's Brigandine"),
    TRIUMPHANT_LAMELLAR("Triumphant Lamellar"),
    // DEX/INT
    PADDED_VEST("Padded Vest"),
    OILED_VEST("Oiled Vest"),
    PADDED_JACKET("Padded Jacket"),
    OILED_COAT("Oiled Coat"),
    SCARLET_RAIMENT("Scarlet Raiment"),
    WAXED_GARB("Waxed Garb"),
    BONE_ARMOUR("Bone Armour"),
    QUILTED_JACKET("Quilted Jacket"),
    SLEEK_COAT("Sleek Coat"),
    CRIMSON_RAIMENT("Crimson Raiment"),
    LACQUERED_GARB("Lacquered Garb"),
    CRYPT_ARMOUR("Crypt Armour"),
    SENTINEL_JACKET("Sentinel Jacket"),
    VARNISHED_COAT("Varnished Coat"),
    BLOOD_RAIMENT("Blood Raiment"),
    SADIST_GARB("Sadist Garb"),
    CARNAL_ARMOUR("Carnal Armour")
}

fun strBodyArmour() =
    listOf(
        BodyArmour.PLATE_VEST,
        BodyArmour.CHESTPLATE,
        BodyArmour.COPPER_PLATE,
        BodyArmour.WAR_PLATE,
        BodyArmour.FULL_PLATE,
        BodyArmour.ARENA_PLATE,
        BodyArmour.LORDLY_PLATE,
        BodyArmour.BRONZE_PLATE,
        BodyArmour.BATTLE_PLATE,
        BodyArmour.SUN_PLATE,
        BodyArmour.COLOSSEUM_PLATE,
        BodyArmour.MAJESTIC_PLATE,
        BodyArmour.GOLDEN_PLATE,
        BodyArmour.CRUSADER_PLATE,
        BodyArmour.ASTRAL_PLATE,
        BodyArmour.GLADIATOR_PLATE,
        BodyArmour.GLORIOUS_PLATE
    )

fun dexBodyArmour() =
    listOf(
        BodyArmour.SHABBY_JERKIN,
        BodyArmour.STRAPPED_LEATHER,
        BodyArmour.BUCKSKIN_TUNIC,
        BodyArmour.WILD_LEATHER,
        BodyArmour.FULL_LEATHER,
        BodyArmour.SUN_LEATHER,
        BodyArmour.THIEFS_GARB,
        BodyArmour.EELSKIN_TUNIC,
        BodyArmour.FRONTIER_LEATHER,
        BodyArmour.GLORIOUS_LEATHER,
        BodyArmour.CORONAL_LEATHER,
        BodyArmour.CUTTHROATS_GARB,
        BodyArmour.SHARKSKIN_TUNIC,
        BodyArmour.DESTINY_LEATHER,
        BodyArmour.EXQUISITE_LEATHER,
        BodyArmour.ZODIAC_LEATHER,
        BodyArmour.ASSASSINS_GARB
    )

fun intBodyArmour() =
    listOf(
        BodyArmour.SIMPLE_ROBE,
        BodyArmour.SILKEN_VEST,
        BodyArmour.SCHOLARS_ROBE,
        BodyArmour.SILKEN_GARB,
        BodyArmour.MAGES_VESTMENT,
        BodyArmour.SILK_ROBE,
        BodyArmour.CABALIST_REGALIA,
        BodyArmour.SAGES_ROBE,
        BodyArmour.SILKEN_WRAP,
        BodyArmour.CONJURERS_VESTMENT,
        BodyArmour.SPIDERSILK_ROBE,
        BodyArmour.DESTROYER_REGALIA,
        BodyArmour.SAVANTS_ROBE,
        BodyArmour.NECROMANCER_SILKS,
        BodyArmour.OCCULTISTS_VESTMENT,
        BodyArmour.WIDOWSILK_ROBE,
        BodyArmour.VAAL_REGALIA
    )

fun strDexBodyArmour() =
    listOf(
        BodyArmour.LIGHT_BRIGANDINE,
        BodyArmour.SCALE_DOUBLET,
        BodyArmour.INFANTRY_BRIGANDINE,
        BodyArmour.FULL_SCALE_ARMOUR,
        BodyArmour.SOLDIERS_BRIGANDINE,
        BodyArmour.FIELD_LAMELLAR,
        BodyArmour.WYRMSCALE_DOUBLET,
        BodyArmour.HUSSAR_BRIGANDINE,
        BodyArmour.FULL_WYRMSCALE,
        BodyArmour.COMMANDERS_BRIGANDINE,
        BodyArmour.BATTLE_LAMELLAR,
        BodyArmour.DRAGONSCALE_DOUBLET,
        BodyArmour.DESERT_BRIGANDINE,
        BodyArmour.FULL_DRAGONSCALE,
        BodyArmour.GENERALS_BRIGANDINE,
        BodyArmour.TRIUMPHANT_LAMELLAR
    )

fun strIntBodyArmour() =
    listOf(
        BodyArmour.CHAINMAIL_VEST,
        BodyArmour.CHAINMAIL_TUNIC,
        BodyArmour.RINGMAIL_COAT,
        BodyArmour.CHAINMAIL_DOUBLET,
        BodyArmour.FULL_RINGMAIL,
        BodyArmour.FULL_CHAINMAIL,
        BodyArmour.HOLY_CHAINMAIL,
        BodyArmour.LATTICED_RINGMAIL,
        BodyArmour.CRUSADER_CHAINMAIL,
        BodyArmour.ORNATE_RINGMAIL,
        BodyArmour.CHAIN_HAUBERK,
        BodyArmour.DEVOUT_CHAINMAIL,
        BodyArmour.LORICATED_RINGMAIL,
        BodyArmour.CONQUEST_CHAINMAIL,
        BodyArmour.ELEGANT_RINGMAIL,
        BodyArmour.SAINTS_HAUBERK,
        BodyArmour.SAINTLY_CHAINMAIL
    )

fun dexIntBodyArmour() =
    listOf(
        BodyArmour.PADDED_VEST,
        BodyArmour.OILED_VEST,
        BodyArmour.PADDED_JACKET,
        BodyArmour.OILED_COAT,
        BodyArmour.SCARLET_RAIMENT,
        BodyArmour.WAXED_GARB,
        BodyArmour.BONE_ARMOUR,
        BodyArmour.QUILTED_JACKET,
        BodyArmour.SLEEK_COAT,
        BodyArmour.CRIMSON_RAIMENT,
        BodyArmour.LACQUERED_GARB,
        BodyArmour.CRYPT_ARMOUR,
        BodyArmour.SENTINEL_JACKET,
        BodyArmour.VARNISHED_COAT,
        BodyArmour.BLOOD_RAIMENT,
        BodyArmour.SADIST_GARB,
        BodyArmour.CARNAL_ARMOUR
    )
